name: Build and Release apk

on:
  push:
    tags:
      - v*

jobs:
  process:
    name: all process
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2.5.0
        with:
          distribution: 'adopt'
          java-version: '11'
      - name: Build with Gradle
        run: chmod +x gradlew &&./gradlew aR
        env:
          PGY_API_KEY: ${{ secrets.PGY_API_KEY }}
          AMAP_KEY: ${{ secrets.AMAP_KEY }}
          NESTOR_KEYSTORE_ALIAS: ${{ secrets.KEY_ALIAS }}
          NESTOR_KEYSTORE_PASSWORD: ${{ secrets.KEY_PASSWORD }}
      - name: Release apk
        uses: ncipollo/release-action@v1
        with:
          artifacts: "**/release/*.apk"
          token: ${{ secrets.MY_GITHUB_ACCESSE }}
#      - name: Upload To Pgyer
#        uses: JantHsueh/upload-file-action@master
#        with:
#          url: https://www.pgyer.com/apiv2/app/upload
#          method: POST
#          forms: '{"_api_key":"${{ secrets.PGY_API_KEY }}","buildInstallType":1,"buildUpdateDescription":"排出定位精度低于15的数据"}'
#          fileForms: '{"file":"app/build/outputs/apk/full/release/app-full-release.apk"}'